//Creating fake object to avoid reaching limit of the fetching the API
export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/nmg2lY4QuyXQrAnrC2lRblK5rT6.jpg",
    genre_ids: [18],
    id: 1416,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Grey's Anatomy",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    popularity: 5902.253,
    poster_path: "/jcEl8SISNfGdlQFwLzeEtsjDvpw.jpg",
    first_air_date: "2005-03-27",
    name: "Grey's Anatomy",
    vote_average: 4.56,
    vote_count: 10005,
  },
];
export const FAKE_RECOMMENDATIONS = [
  {
    backdrop_path: "/1vwIV2zQ88Dx6PwY7ZFZyamhYhV.jpg",
    id: 76773,
    original_name: "Station 19",
    overview:
      "A group of heroic firefighters at Seattle Fire Station 19—from captain to newest recruit—risk their lives and hearts both in the line of duty and off the clock. These brave men and women are like family, literally and figuratively, and together they put their own lives in jeopardy as first responders to save the lives of others.",
    poster_path: "/kxao9HIrGO60EhrCRhSBQ3p3XL0.jpg",
    media_type: "tv",
    adult: false,
    name: "Station 19",
    original_language: "en",
    genre_ids: [18, 10759],
    popularity: 256.552,
    first_air_date: "2018-03-22",
    vote_average: 8.232,
    vote_count: 1421,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/f3cin9kOz4nOrlYEMxGFQhv4bdN.jpg",
    id: 71712,
    original_name: "The Good Doctor",
    overview:
      "Shaun Murphy, a young surgeon with autism and savant syndrome, relocates from a quiet country life to join a prestigious hospital's surgical unit. Unable to personally connect with those around him, Shaun uses his extraordinary medical gifts to save lives and challenge the skepticism of his colleagues.",
    poster_path: "/53P8oHo9cfOsgb1cLxBi4pFY0ja.jpg",
    media_type: "tv",
    adult: false,
    name: "The Good Doctor",
    original_language: "en",
    genre_ids: [18],
    popularity: 767.445,
    first_air_date: "2017-09-25",
    vote_average: 8.492,
    vote_count: 12155,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/euuK8owCrdiz0HMj8iVhhquPhDv.jpg",
    id: 4614,
    original_name: "NCIS",
    overview:
      "From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position.",
    poster_path: "/2exOHePjOTquUsbThPGhuEjYTyA.jpg",
    media_type: "tv",
    adult: false,
    name: "NCIS",
    original_language: "en",
    genre_ids: [80, 18, 10759],
    popularity: 905.299,
    first_air_date: "2003-09-23",
    vote_average: 7.63,
    vote_count: 2194,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/r0Q6eeN9L1ORL9QsV0Sg8ZV3vnv.jpg",
    id: 1408,
    original_name: "House",
    overview:
      "Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.",
    poster_path: "/3Cz7ySOQJmqiuTdrc6CY0r65yDI.jpg",
    media_type: "tv",
    adult: false,
    name: "House",
    original_language: "en",
    genre_ids: [18, 9648],
    popularity: 622.093,
    first_air_date: "2004-11-16",
    vote_average: 8.596,
    vote_count: 6281,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/hib8MpBPU7GdluS38htXCF4uw0c.jpg",
    id: 2734,
    original_name: "Law & Order: Special Victims Unit",
    overview:
      "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.",
    poster_path: "/onmSVwYsPMYtO8OjLdjS8FfRNKb.jpg",
    media_type: "tv",
    adult: false,
    name: "Law & Order: Special Victims Unit",
    original_language: "en",
    genre_ids: [80, 18, 9648],
    popularity: 1351.552,
    first_air_date: "1999-09-20",
    vote_average: 7.921,
    vote_count: 3700,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/9hfA9zMsyckwZ8WLMVQYKG8YSwY.jpg",
    id: 80350,
    original_name: "New Amsterdam",
    overview:
      "The new medical director breaks the rules to heal the system at America's oldest public hospital. Max Goodwin sets out to tear up the bureaucracy and provide exceptional care, but the doctors and staff are not so sure he can succeed. They've heard this before. Not taking \"no\" for an answer, Dr. Goodwin's instinctive response to problems large and small is four simple words: \"How can I help?\" He has to disrupt the status quo and prove he'll stop at nothing to breathe new life into this underfunded and underappreciated hospital, returning it to the glory that put it on the map.",
    poster_path: "/jsH4AeGZn5Q6h314A3OTUHKxHhR.jpg",
    media_type: "tv",
    adult: false,
    name: "New Amsterdam",
    original_language: "en",
    genre_ids: [18],
    popularity: 176.91,
    first_air_date: "2018-09-25",
    vote_average: 8.382,
    vote_count: 945,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/nVRyd8hlg0ZLxBn9RaI7mUMQLnz.jpg",
    id: 1622,
    original_name: "Supernatural",
    overview:
      "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ",
    poster_path: "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg",
    media_type: "tv",
    adult: false,
    name: "Supernatural",
    original_language: "en",
    genre_ids: [18, 9648, 10765],
    popularity: 1568.403,
    first_air_date: "2005-09-13",
    vote_average: 8.294,
    vote_count: 7328,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/e9n87p3Ax67spq3eUgLB6rjIEow.jpg",
    id: 1911,
    original_name: "Bones",
    overview:
      "Dr. Temperance Brennan and her colleagues at the Jeffersonian's Medico-Legal Lab assist Special Agent Seeley Booth with murder investigations when the remains are so badly decomposed, burned or destroyed that the standard identification methods are useless.",
    poster_path: "/eyTu5c8LniVciRZIOSHTvvkkgJa.jpg",
    media_type: "tv",
    adult: false,
    name: "Bones",
    original_language: "en",
    genre_ids: [80, 18],
    popularity: 1040.373,
    first_air_date: "2005-09-13",
    vote_average: 8.246,
    vote_count: 3073,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/k7T9xRyzP41wBVNyNeLmh8Ch7gD.jpg",
    id: 18165,
    original_name: "The Vampire Diaries",
    overview:
      "The story of two vampire brothers obsessed with the same girl, who bears a striking resemblance to the beautiful but ruthless vampire they knew and loved in 1864.",
    poster_path: "/gbp4zM0FE0n23X4UFY5EBlacrog.jpg",
    media_type: "tv",
    adult: false,
    name: "The Vampire Diaries",
    original_language: "en",
    genre_ids: [18, 10765],
    popularity: 877.31,
    first_air_date: "2009-09-10",
    vote_average: 8.336,
    vote_count: 8753,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/dhnHhEugKPohoyigCaFywPfOJBp.jpg",
    id: 75219,
    original_name: "9-1-1",
    overview:
      "Explore the high-pressure experiences of police officers, paramedics and firefighters who are thrust into the most frightening, shocking and heart-stopping situations. These emergency responders must try to balance saving those who are at their most vulnerable with solving the problems in their own lives.",
    poster_path: "/ax6YyNcPsuPbKze9hxdH4dU3e9w.jpg",
    media_type: "tv",
    adult: false,
    name: "9-1-1",
    original_language: "en",
    genre_ids: [18, 80, 10759],
    popularity: 433.733,
    first_air_date: "2018-01-03",
    vote_average: 8.213,
    vote_count: 2373,
    origin_country: ["US"],
  },
];
