//It is the base url from the movie db
const BASE_URL = "https://api.themoviedb.org/3/";
//API key generated by the MOVIE DB
const API_KEY_PARAM = "?api_key=de0686bae09a849c49800b28ce647352";
// Starting URL for the background images
const BACKDROP_BASE_URL = "https://image.tmdb.org/t/p/original";
const SMALL_IMG_COVER_BASE_URL = "https://image.tmdb.org/t/p/w300";
export { BASE_URL, API_KEY_PARAM, BACKDROP_BASE_URL, SMALL_IMG_COVER_BASE_URL };
